name: Shellcheck

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.sh'
  push:
    branches: [ main ]
    paths:
      - '**/*.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: Shellcheck
    steps:
      - uses: actions/checkout@v4
      
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          format: gcc
          severity: error
        env:
          SHELLCHECK_OPTS: -e SC1091